#https://github.com/marketplace/actions/automated-version-bump

name: "Bump Version"

on:
  #push:
  #  branches:
  #    - "master"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version-type:
        type: choice
        description: ➕ Given a version number MAJOR.MINOR.PATCH, what should we increment (and tag)?
        options: 
        - major
        - minor
        - patch

jobs:
  bump-version:
    name: "Bump Version"
    runs-on: ubuntu-latest
    # runs-on: [ self-hosted, tests ]

    env:
      COMPOSER_DIRECTORY: "."
      COMPOSER_FILE_PATH: "./composer.json"

    # Map a step output to a job output
    outputs:
      newTag: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Dump GitHub context
        id: github_context_step
        run: |
          echo '🔎 GitHub context is:\n${{ toJSON(github) }}'
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "🔎 check current version in composer.json"
        run: cat ${{env.COMPOSER_FILE_PATH}} | grep version

      - run: echo "running job for input ${{ github.event.inputs.version-type }}"
       
      - name: "🏷️ Bump Version"
        id: version-bump
        uses: "corsi-it/gh-action-bump-composer-version@main"
        with:
          tag-prefix: "v"
          minor-wording:  'minor'
          major-wording:  'major'
          patch-wording:  'patch'
          commit-message: "CI: bumps version using '${{ github.event.inputs.version-type }}' [skip ci]"
        env:
          COMPOSERJSON_DIR: ${{env.COMPOSER_DIRECTORY}}
          # TOKEN_WORKAROUND is a personal token, set at organization level, to bypass branch protection rules
          # this must be also set in actions/checkout@v4 action: https://github.com/phips28/gh-action-bump-version/issues/62
          GITHUB_TOKEN: ${{ secrets.TOKEN_WORKAROUND }}

      - name: "🔎 check new version in composer.json"
        run: cat ${{env.COMPOSER_FILE_PATH}} | grep version

      - name: "🎉 Write new tag"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
